/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tombola

import isValidClaim
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class AppTest {
    @Test
    fun `claim should be accepted if claimed right after winning for top row`() {
        val result = isValidClaim(
            listOf(setOf(4, 16, 48, 63, 76), setOf(7, 23, 38, 52, 80), setOf(9, 25, 56, 64, 83)),
            listOf(90, 4, 46, 63, 89, 16, 76, 48),
            "top"
        )

        assertTrue(result)
    }

    @Test
    fun `claim should be rejected if not claimed right after winning for top row`() {
        val result = isValidClaim(
            listOf(setOf(4, 16, 48, 63, 76), setOf(7, 23, 38, 52, 80), setOf(9, 25, 56, 64, 83)),
            listOf(90, 4, 46, 63, 89, 16, 76, 48, 72),
            "top"
        )

        assertFalse(result)
    }
}
